### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [xant/libhl#12]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/xant/libhl/blob/79bb163d100a9d376da9a6056c8585c809f2b4e9/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by xant** [comment]
I considered using those but I think the project is too small and simple to justify such a migration to other building tools. Makefile seems sufficient to me so far and in my personal cases it also simplified inclusion in other projects.
If you feel like attempting the introduction of autotools (autoconf/automake to generate the makefiles) let me have a patch and I'll consider inclusion, otherwise I think I won't approach this subject again until things will become big enough to be unmanageable with a simple makefile or if some logic will need to know more about the architecture it's running on, justifying a configure phase.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?
