### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by graphitemaster** [xant/libhl#8]
Some quick initial review of libhl turned up some issues with it.

 * The use of ```__USE_UNIX98``` is a non-standard feature-test macro which should be replaced with ```_POSIX_C_SOURCE```.

* There are a lot of identifiers that begin with double underscore, for instance ```__foo```. These identifiers are reserved by the implementation (compiler and libc.) perhaps using an ```hl_``` prefix would be better. This is also seen in headers a lot too; ```__BINOMIAL_HEAP_H__``` for instance.

* Failure to use `extern "C"` in headers for `__cplusplus` This makes it hard to actually use the library for C++ as the symbol names can be mangled, thus not finding them at link stage.

* ```#pragma pack(push, ...)``` is seen a lot. I'm not sure why you're packing these structures, for doing so can only lead to access violations on systems where the read/write may be unaligned and therefor illegal (PPC for instance.)

* Checking for ```NULL``` when calling ```free```. This is just redundant as ```free``` is required to do this check. Doing this only leads to false-positives when running the code through static-analysis tools like coverity.

* Linked list is not thread-safe. ```get_entry_position``` needs to hold a lock for a new list node can be inserted into the list in another thread causing the position to be wrong. This can cause a whole slew of problems.

* Failure to check return value of ```malloc```. It can fail, without checking and handling this case, this library is not usable for robust systems.

**Comment by xant** [comment]
ok ... some are good points ... some others not.
I'll replace __USE_UNIX98 with __POSIX_C_SOURCE.
Actually I used this library from c++ so what was the problem you were having exactly ? .. it might be that some of the more recent source hasn't been wrapped with extern "C" ... could you show me the output of your compiler?

The #pragma pack is pretty safe and it's handled by the compiler if possible. It will be ignored if not applicable. When taken into account (which is always where I run this library) it has an effect on the size of certain structures and give some benefits in specific use cases. But since it's generally safe I wouldn't bother.

I'll fix get_entry_position if that's the case.
Wrapping malloc calls don't make any sense to me since if you ran out of memory your program should die. If you think it would add robustness let me see a patch and I'll be glad to review it. But in general failing gracefully if out of memory is not an option, since the outer code will probably fail as well.

The use of '__' is completely legit and actually is a sort of standard (did you ever grep for "define __" in /usr/include/** ?)

**Comment by elfring** [comment]
* I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

  Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by xant** [comment]
could you make an example where return values are ignored please?
(or better push a patch if you think there is something wrong)

**Comment by elfring** [comment]
How do you think about care also for [the return value from the call of a function like "pthread_mutex_init"](https://github.com/xant/libhl/blob/1861005589639e60c3933f681aef21564a9dec4d/src/linklist.c#L81 "Update candidate: list_init()")?

Would you like to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

**Comment by elfring** [comment]
Do you want that these source files should only be safely reused within the implementations of compilers for [the programming languages "C" and "C++"](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by xant** [comment]
ok ... added some extra checks to fail gracefully when out of memory conditions happen.
Also mutex and attrs initialization is checked ...  if you have any hint on how to improve the static analyzer you are more than welcome , so far though I didn't see the clang static analyzer having any problem.
I can't understand your last comment.
Thanks for your time and let me know if you see anything else worth improving :)

**Comment by elfring** [comment]
>... if you have any hint on how to improve the static analyzer ...

How do you think about to try any more source code analysis tools out?
Are there [a few update candidates](https://github.com/xant/libhl/blob/4baaddba421461c4d02a9ffbf36d021938eac902/src/hashtable.c#L27 "Checking with 'spin'?") left over?

>I can't understand your last comment.

Would you like to avoid to tamper with identifiers in the reserved name space more than it is absolutely necessary?

**Comment by xant** [comment]
are you sure that the "a few update candidates" link you posted points to the right place?

also, about tampering with the reserved name space, do you refer to the preprocessor symbols on top of the header files?
maybe I could use a single underscore instead of two ?  but did you have any name clash so far?
did you check if it's common practice to use such identifiers (__<UPPERCASE_FILENAME>_H__) on top of C header files? 

(I don't know if I like this game of talking only by questions .... anyway .... I'll close this issue, if you see any problem please start a new issue and attach some useful information to fix or improve the code instead of playing the riddle game)

**Comment by elfring** [comment]
>are you sure that the "a few update candidates" link you posted points to the right place?

Yes. - My link pointed to more functions from the POSIX thread programming interface for [further considerations](https://github.com/xant/libhl/blob/4baaddba421461c4d02a9ffbf36d021938eac902/src/hashtable.c#L374 "Update candidate: ht_set_list()").

>also, about tampering with the reserved name space, ...

@graphitemaster pointed similar concerns out for the identifier selection. It will be safer to replace some underscores by an unique prefix or delete them.

**Comment by elfring** [comment]
>..., if you see any problem please start a new issue ...

The software improvement can be continued with bug reports like the following.
* [Completion of error handling](https://github.com/xant/libhl/issues/9 "More exception handling?")
* [Reserved identifier violation](https://github.com/xant/libhl/issues/10 "Reconsider identifier selection")

**Comment by graphitemaster** [comment]
>The use of '__' is completely legit and actually is a sort of standard (did you ever grep for "define __" in /usr/include/** ?)

Files in /usr/include are the files provided by the implementation. They are allowed to use the double underscore. You as a library cannot however as the standard explicitly states that anything beginning with double underscore is reserved by the implementation. It's legal for stdio.h for instance to expose a macro like ```#define __foo int``` If your code now uses this identifier, bad things will happen.

Check 7.1.3 Reserved identifiers in the C99 specification which states
> All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use. 

I did not suggest to wrap malloc calls. I suggested checking their return status to see if they return ```NULL``` and to gracefully propagate this error back up the call stack and indicate error to the user of the library. A library that cannot indicate failure of memory allocation is not usable in a robust environment where having a service just unexpectedly crash because of OOM just isn't allowed. Flight control software for instance.

**Comment by xant** [comment]
Have you checked the changes from yesterday?
I think the library now properly handles OOM conditions and return back an error to the caller.
Now, I can understand the point if you are going to use this library in some realtime application but if you run on a generic unix system and you run out of memory chances are that your process will be killed by the system or that your program will just crash next time you call any function from the standard library or not (consider that apart a few functions which return back an error when out of memory, many other will just crash).
Now, I'm not saying that you shouldn't care about such out-of-memory cases, but I think you should handle certain conditions only in contexts where it makes sense
(for instance advising to always check the return value of pthread_mutex_lock() doesn't make any sense in 99% of contexts).
I understand that such a library is pretty generic so I shouldn't have assumed anything and just let the caller make the decision ... hence the recent improvements thanks to your suggestions.
But next time a simple patch instead of a series of allusive comments and references to guidelines and conventions would be better and more appreciated.
In the end if you don't like this library on you don't trust the code, you can just not use it ;)
If instead you are going to use it, please try being more constructive in the feedbacks and provide some code.

**Comment by elfring** [comment]
>... for instance advising to always check the return value of pthread_mutex_lock() doesn't make any sense in 99% of contexts ...

I recommend to prepare the source code of this basic data structure library also for the consistent handling of exceptional situations.


>But next time a simple patch instead of a series of allusive comments and references to guidelines and conventions would be better and more appreciated.

It is occasionally more convenient when contributions are provided in the source code language directly. But software evolution will need some consensus before proposed changes will be accepted.
There are further design options available to choose the preferred solution.

**Comment by graphitemaster** [comment]
I understand that patches are more helpful than a series of elusive comments. However some of us are prevented from providing actual working source code due to non compete clauses preventing us from achieving that. Consider feedback the only choice in that circumstance.

**Comment by dgryski** [comment]
@graphitemaster if you're using this in a commercial project,  it might be nice to provide @xant some contact work to fix these issues.

**Comment by xant** [comment]
Non competition caluses and non disclosure agreements are pretty common in the software development industry. But unless your business is about building libraries for basic datastructures and standard algorithms, I don't see how contributing with fixes/improvements to such an opensource component might fall into such caluses.
And in general, for any kind of business, if you end up employing some opensource component, it would be nice to contribute back with some actual patches or at least with clear and explanatory feedback.
Also being nice and polite would help, even if this is not strictly necessary.
