### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [xant/libhl#9]
1. Would you like to add more error handling for return values from functions like the following?
  * [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [list_sort](https://github.com/xant/libhl/blob/4baaddba421461c4d02a9ffbf36d021938eac902/src/linklist.c#L1184)
  * [pthread_spin_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_spin_init.html "Initialize a spin lock object.") ⇒ [ht_set_list](https://github.com/xant/libhl/blob/4baaddba421461c4d02a9ffbf36d021938eac902/src/hashtable.c#L374)
2. How do you think about to annotate any functions with "[`__attribute__((warn_unused_result))`](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Function-Attributes.html#index-g_t_0040code_007bwarn_005funused_005fresult_007d-function-attribute-3299 "Warn on unused results?")"?

**Comment by xant** [comment]
pthread_mutex_lock() will fail if:

     [EDEADLK]          A deadlock would occur if the thread blocked waiting for mutex.

     [EINVAL]           The value specified by mutex is invalid.

actually EDEADLK happens only if specific attributes are passed to PTHREAD_MUTEX_INIT (not our case)
EINVAL only if the muxs is not valid which is not possible because initialization is checked (and memory corruption is not an option).
So checking the return value of pthread_mutex_lock() is superfluous.

**Comment by jhi** [comment]
On Thursday-201508-27 14:30, Andrea Guzzo wrote:
> |pthread_mutex_lock() will fail if: [EDEADLK] A deadlock would occur if
> the thread blocked waiting for mutex. [EINVAL] The value specified by
> mutex is invalid. |
>
> actually EDEADLK happens only if specific attributes are passed to
> PTHREAD_MUTEX_INIT (not our case)
> EINVAL only if the muxs is not valid which is not possible because
> initialization is checked (and memory corruption is not an option).
> So checking the return value of pthread_mutex_lock() is superfluous.

You are assuming here a 100% compliant (nothing missing, nothing added, 
and completely forever unchanging) implementation.  This is, usually, a 
fantasy. Just check the value.

**Comment by xant** [comment]
but are you really suggesting to always check the return value of pthread_mutex_lock() ? ... because this sounds quite unreasonable to me.

Or are we talking here about shutting up some specific static analyzer complaining about it ?

Because in this case , really, the only problem could be memory corruption, and it's a waste of time to protect from that (since it shouldn't happen and that's it)

**Comment by elfring** [comment]
I would prefer that strict error detection will become less optional in important software.
Is [the importance of software robustness](https://en.wikipedia.org/w/index.php?title=Robustness_%28computer_science%29 "Making software more robust?") increasing for the affected data structure library?


Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by jhi** [comment]
On Thursday-201508-27 14:46, Andrea Guzzo wrote:
> but are you really suggesting to always check the return value of
> pthread_mutex_lock() ? ... because this sounds quite unreasonable to me.

Are you religiously opposed to checking return values?

**Comment by xant** [comment]
no ... and you can definitely notice it from the code.
I just don't see why you should check pthread_mutex_lock() specifically.
Apart memory corruption ... what could make it fail?
Have you looked at other important software sourcecode?
I have no problem in checking it everytime and I will probably do it. But I need to understand why it is necessary and why nobody else does it (since my understanding is that apart for memory corruption or some other specific behaviours there is no point in checking for the return value from pthread_mutex_lock())

**Comment by jhi** [comment]
>
>
> I just don't see why you should check pthread_mutex_lock() specifically.
>

I'm not saying one should check for pthread_mutex_lock() *specifically*.

I'm saying that if something *can* fail, one should check for it.

Arguing "but it cannot fail in this particular case" is in my opinion
wasted effort (note also my earlier comment about implementations being
imperfect), the effort is better spent in just adding the check and moving
on.

-- 
There is this special biologist word we use for 'stable'. It is 'dead'. --
Jack Cohen

**Comment by xant** [comment]
so are you talking "generically" ? ... do you think I don' take into account that things can fail? :)

**Comment by jhi** [comment]
so are you talking "generically" ? ... do you think I don' take into
> account that things can fail? :)
>

Again, you are reading into my messages something I am not saying.

-- 
There is this special biologist word we use for 'stable'. It is 'dead'. --
Jack Cohen

**Comment by xant** [comment]
I'm just trying to understand what should be changed here.
I agree with everything said/referred by elfring and I already wrapped allocations 
(since I understand that in certain environments you can't rely on allocators as you do generally on unix systems).
But I still don't see how does this apply to pthread_mutex_lock() and if I should really check all calls to certain pthread functions ... which I think should require more explanations considering my previous points.

**Comment by elfring** [comment]
>... and why nobody else does it ...

Can strict error detection become tedious in procedural programming languages like C?
Would you like to look at relevant error predicates again in more detail?

There are some software development methodologies evolving which could help you here.

**Comment by xant** [comment]
my guess is that since that mutex is recursive his static analyzer complains about not checking the return value of pthread_mutex_lock() ... but in this case the only thing would be distinguishing between a memory corruption (bad ... your program should crash!) and a EDEADLCK reported (which is the normal condition here) ... so if we want to change the code to shut up the static analyzer, just provide a patch for it or say which satic analyzer is complaining so I can test myself (instead of going ahead with riddles)

**Comment by xant** [comment]
elfring, can you point me out to some serious big software which actually checks all calls to the pthread interface (apart for specific reasons) ?
Please ... or tell me why it is so important ... the change is trivial , error detection is not tedious but it has to make sense

**Comment by elfring** [comment]
I hope that [open issues around a weakness 252](https://cwe.mitre.org/data/definitions/252.html "Unchecked return value") can also be reduced in this software library for basic data structures.

**Comment by xant** [comment]
lol :D .... now  I know you are talking bullshit :)
so the things are three : 
- or you are trying to run this library on some specific system and you need this kind of compliance (I would wonder what ... a space shuttle? :D)
- or you want some stuff fixed because your static analyzer complains and you don't understand what it is talking about (output from the analyzer might help ...or even knowing which one)
- you are just trolling

**Comment by elfring** [comment]
>... a space shuttle?

I hope that more complete API exception handling is not rocket science.   ;-)


>... because your static analyzer complains and you don't understand what it is talking about ...

I do understand my source code analysis well.


>... trolling

I'm sorry when I hurt your software development feelings a bit.

**Comment by xant** [comment]
please attach the output from the analyzer or point out some specific problem.
Until then this issue is closed.

**Comment by elfring** [comment]
I guess that the concrete source code analysis tool does not really matter as long as it seems that you take corresponding suggestions personally.
I hope that our different software development opinions can still be clarified for remaining update candidates in a constructive way a bit later.

**Comment by xant** [comment]
I just didn't get anything concrete about some sort of riddle games and reference to guidelines and other not-relevant stuff.
It seems to me you are just wasting my time ... I tried getting out something useful from what you said and applied some patches ... but I can't see anything more apart a silly game of allusive questions and "opinions" not supported by actual concrete points.

**Comment by elfring** [comment]
I suggest to follow good software development practices a bit more.
Does [the SEI CERT C Coding Standard](https://www.securecoding.cert.org/confluence/display/c/SEI+CERT+C+Coding+Standard "Secure C coding") matter for you?

**Comment by xant** [comment]
thanks, I'll follow your suggestion :)
I'll also give a look at your code for reference ;)

**Comment by elfring** [comment]
A few update candidates are still left over:
* How do you think about to make the response for an error code configurable so that the user of your software library can choose if an other reaction is preferred than [an abort() call](https://github.com/xant/libhl/commit/73432dbd8f0f502e9cd7e7033b62cd8000db1e70#diff-3f6cde8f5a25df500006dc2e10918f5aR34 "Minor cleanings to allow inclusion in C++ projects") after an error predicate check?
* Which reaction will be appropriate for a failed call of the function "[malloc](https://github.com/xant/libhl/blob/bdb0409dc5d0406657d19d973e4a9b7601704d9c/src/binheap.c#L44 "Update candidate: incr_key_default()")" (or "pthread_spin_init")?

**Comment by elfring** [comment]
Does a tool like "[Coverity Scan](https://scan.coverity.com/projects/xant-libhl "Coverity Scan Static Analysis for libhl")" show any open issues which we discussed here?

**Comment by xant** [comment]
not anymore from what I saw yesterday after 6c07aefcb2e088e3e029ccc8e10d2221a0677c6c

**Comment by elfring** [comment]
Will it be interesting then to clarify the issues I mentioned before?
